catalog:
  minio_local:
    type: sql
    uri: sqlite:///catalog.db
    warehouse: s3://iceberg-warehouse/
    s3.endpoint: http://localhost:9000
    s3.access-key-id: minioadmin
    s3.secret-access-key: minioadmin
    s3.region: us-east-1
    s3.path-style-access: true