[project]
name = "iceberg-etl-demo"
version = "0.1.0"
description = "Learning Iceberg ETL with DuckDB"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "duckdb>=1.3.2",
    "pandas>=2.3.2",
    "pyarrow>=17.0.0,<20.0.0",
    "pyiceberg[sql-sqlite,duckdb,s3]>=0.9.0",
]